# Generated by Django 6.0 on 2025-12-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_menuday_menuitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuday',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='menuday',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='menuday',
            name='date',
        ),
    ]
