# Generated by Django 6.0 on 2025-12-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_alter_menuday_options_alter_menuday_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuday',
            name='day',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], default='', max_length=10),
        ),
    ]
