# Generated by Django 6.0 on 2025-12-18 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_food_item'),
        ('sellers', '0003_menuday_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.menuitem'),
        ),
    ]
